cmdb/urls.py
from django.urls import path
from . import views

app_name = 'cmdb'
urlpatterns = [
    path('list/', views.serverlist, name='list'),
    path('list/add/', views.serveradd, name='list_add'),
    path('list/del/<int:pk>', views.serverdel, name='list_del'),
    path('list/edit/<int:pk>/', views.serveredit, name='list_edit'),
    path('handler/ssh/<ip>', views.invokessh, name='ssh'),
    path('handler/scp/', views.invokescp, name='scp'),
]

deploy/urls.py
from django.urls import path

from . import views


app_name = 'deploy'
urlpatterns = [
    path('list/', views.serverlist, name='deploy'),
]

platfrom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cmdb/', include('cmdb.urls', namespace='cmdb')),
    path('deploy/', include('deploy.urls', namespace='deploy')),
]

cmdb/models.py
from django.db import models

SYSTEM_LIST = (
    ('redhat', 'redhat'),
    ('opensuse', 'opensuse'),
    ('ubuntu', 'ubuntu'),
    ('centos', 'centos'),
    ('windows', 'windows'),
    ('other', 'other'),
)

STATUS = (
    ('produce', 'produce'),
    ('test', 'test'),
    ('other', 'other'),
)


class Project(models.Model):
    name = models.CharField(max_length=50)
    owner = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class ServerDetail(models.Model):
    ip = models.CharField(max_length=20, unique=True)
    system = models.CharField(choices=SYSTEM_LIST, default='centos', max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    cpuinfo = models.CharField(max_length=50)
    memory = models.IntegerField()
    status = models.CharField(choices=STATUS, default='other', max_length=50)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.ip

deploy/models.py
from django.db import models

cmdb/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import ServerDetail
from .froms import ServerDetailForm

import win32api



def serverlist(request):
    objs = ServerDetail.objects.all()
    return render(request, 'cmdb/list.html', {'objs': objs})


def serveradd(request):
    if request.method == 'POST':
        form = ServerDetailForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list')
    else:
        form = ServerDetailForm()
    return render(request, 'cmdb/add.html', {'form': form})


def serveredit(request, pk):
    obj = get_object_or_404(ServerDetail, pk=pk)
    if request.method == 'POST':
        form = ServerDetailForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('cmdb:list')
    else:
        form = ServerDetailForm(instance=obj)
    return render(request, 'cmdb/edit.html', {'form': form, 'obj': obj})


def serverdel(request, pk):
    obj = get_object_or_404(ServerDetail, pk=pk)
    obj.delete()
    return redirect('cmdb:list')


def invokessh(request, ip):
    agr = '-ssh root@' + ip
    win32api.ShellExecute(0, 'open', 'putty.exe ', agr, '', 1)
    return redirect('cmdb:list')


def invokescp(request):
    win32api.ShellExecute(0, 'open', 'C:\Program Files (x86)\WinSCP\WinSCP.exe', '', '', 1)
    return redirect('cmdb:list')

deploy/views.py
from django.shortcuts import render

from cmdb.models import ServerDetail
import json
import shutil
# from collections import namedtuple
# from ansible.parsing.dataloader import DataLoader
# from ansible.vars.manager import VariableManager
# from ansible.inventory.manager import InventoryManager
# from ansible.playbook.play import Play
# from ansible.executor.task_queue_manager import TaskQueueManager
# from ansible.plugins.callback import CallbackBase



def serverlist(request):
    objs = ServerDetail.objects.all()
    return render(request, 'deploy/list.html', {'objs': objs})


#

# def exec_task(module_name, module_args, host_list, option_dict):
#     # namedtuple命名元组，使用属性名访问
#     Options = namedtuple('Options',
#                          ['connection', 'module_path', 'forks', 'become', 'become_method', 'private_key_file',
#                           'become_user', 'remote_user',
#                           'check', 'diff'])
#
#     options = Options(connection='local', module_path=None, forks=10, become=option_dict['become'],
#                       become_method='sudo', private_key_file="/root/.ssh/id_rsa",
#                       become_user='root', remote_user=option_dict['remote_user'], check=False, diff=False)
#
#     loader = DataLoader()
#     passwords = dict(vault_pass='secret')
#
#     result_callback = ResultCallback()
#
#     # sources指定 host config file or hostname
#     # 创建清单，并传递给VariableManager
#     inventory = InventoryManager(loader=loader, sources=['/etc/ansible/hosts'])
#     variable_manager = VariableManager(loader=loader, inventory=inventory)
#
#     host = ",".join(host_list)
#     play_source = dict(
#         name="Ansible Play",
#         hosts=host,
#         gather_facts='no',
#         tasks=[
#             dict(action=dict(module=module_name, args=module_args), register='shell_out'),
#         ]
#     )
#
#     play = Play().load(play_source, variable_manager=variable_manager, loader=loader)
#
#     tqm = None
#
#     tqm = TaskQueueManager(
#         inventory=inventory,
#         variable_manager=variable_manager,
#         loader=loader,
#         options=options,
#         passwords=passwords,
#         stdout_callback=result_callback,    )
#
#     result = tqm.run(play)
#
#     result_raw = {'success': {}, 'failed': {}, 'unreachable': {}}
#
#     for host, result in result_callback.host_ok.items():
#         result_raw['success'][host] = result._result['stdout_lines']
#
#     for host, result in result_callback.host_failed.items():
#         result_raw['failed'][host] = result._result['stderr_lines']
#
#     for host, result in result_callback.host_unreachable.items():
#         result_raw['unreachable'][host] = result._result['msg']
#
#     return json.dumps(result_raw, indent=4)


def task(request):
    pass

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="{% static 'js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">{% block sidebar %}{% endblock %}</div>
        <div class="col-md-10">{% block content %}{% endblock %}</div>
    </div>
</div>
</body>
{% include 'modal.html' %}
</html>

templates/cmdb/add.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{% url 'cmdb:list_add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

    </form>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="'modal">Close</button>
        <button type="button" class="btn btn-primary">Save</button>
    </div>
</div>
{% endblock %}

templates/cmdb/edit.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{% url 'cmdb:list_edit' obj.pk %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div class="form-control">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
    </form>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="'modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>
{% endblock %}

templates/cmdb/list.html
{% extends 'base.html' %}
{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}

{% block content %}
    <div>
        <button class="btn-sm btn-light"><a href="{% url 'cmdb:list_add' %}">新增</a></button>
        <button class="btn-sm btn-light">批量删除</button>
        <table class="table table-bordered">
            <thead class="thead-light">
            <tr>
                <th scope="col">序号</th>
                <th scope="col">IP地址</th>
                <th scope="col">项目名称</th>
                <th scope="col">状态</th>
                <th scope="col">分类</th>
                <th scope="col">ssh</th>
                <th scope="col">FTP</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in objs %}
                <tr>
                    <td>{{ obj.pk }}</td>
                    <td>{{ obj.ip }}</td>
                    <td>{{ obj.project.name }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>{{ obj.category.name }}</td>
                    <td><a href="{% url 'cmdb:ssh' obj.ip %}" class="btn-sm btn-dark">连接</a></td>
                    <td><a href="{% url 'cmdb:scp' %}" class="btn-sm btn-dark">上传</a></td>
                    <td>
                        <a href="{% url 'cmdb:list_edit' obj.pk %}" data-toggle="modal" data-target="#myModal"
                           class="btn-sm btn-dark">编辑</a>
                        {#                    <a href="{% url 'list_edit' obj.pk %}" class="btn-sm btn-dark">编辑</a>#}
                        <a class="btn-sm btn-dark" href="{% url 'cmdb:list_del' obj.pk %}">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'modal.html' %}

    </div>
{% endblock %}

templates/deploy/list.html
{% extends 'base.html' %}

{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <label for="server_list">
                    <span>服务器列表：</span>
                </label>
            </div>
            <div class="col-md-4">
                <select name="#" id="server_list" multiple="multiple">
                    {% for obj in objs %}
                        <option value="#">{{ obj.ip }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-2" id="server_move" >
                <div>
                    <input type="button" id="right_move" value="右移">
                </div>
                <div>
                    <input type="button" id="left_move" value="左移">
                </div>
            </div>
            <div class="col-md-4">
                <select name="#" id="server_list_execute" multiple="multiple">

                </select>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-10">
                <div class="input-group">
                    <input type="text" class="#">
                    <button type="submit">执行</button>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-10">
                <textarea name="" id="" cols="30" rows="10"></textarea>
                <button type="submit">执行</button>
            </div>
        </div>
    </div>
    <div>
    </div>
{% endblock %}

templates/deploy/task.html
{% extends 'base.html' %}

{% block content %}
        <div class="col-md-10">
            <input type="text" class="#">
            <button type="submit">执行</button>
        </div>
        <br>
        <div class="col-md-10">
            <textarea name="" id="" cols="30" rows="10"></textarea>
            <button type="submit">执行</button>
        </div>
{% endblock %}

templates/modal.html
<div class="modal fade" id="myModal" tabindex="-1" , role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">

            </div>
                       <div>
                           <button type="button" class="btn btn-secondary" data-dismiss="'modal">关闭</button>
                           <button type="submit" class="btn btn-primary">保存</button>
                       </div>
        </div>
    </div>
</div>

templates/sidebar.html
{% load staticfiles %}


<div>
    <ul class="list-group">
        <li class="list-group-item " ><a href="{% url 'cmdb:list' %}">服务器列表</a></li>
        <li class="list-group-item "><a href="{% url 'deploy:deploy' %}">服务部署</a></li>
        <li class="list-group-item "><a href="#">定时任务</a></li>
        <li class="list-group-item "><a href="#">数据备份</a></li>
    </ul>
</div>